Carlos
UEHG260899/dipu-net pull request #13
Opened 2021-06-14 21:02 UTC by CarlosSerranoV

*Maquetado Home escritor
*Maquetado crear artículo
*Sección  datos estadísticos en vista  home escritor
*Sección  carrusel artículos publicados en vista  home escritor
*Sección  carrusel artículos guardados en vista  home escritor
*Sección ver pre articulo en vista crear artículo

2021-06-14 21:10 UTC, UEHG260899 requested changes

2021-06-14 21:10 UTC, UEHG260899 commented on css/styles.css
> +:root {
Quita todo el archivo, que este lo hizo Apodaca y lo pusiste en tu rama

2021-06-14 21:10 UTC, UEHG260899 commented on php/Escritor/articulo/crear.php
> +<style>
Seria bueno poner los estilos en una hoja aparte

2021-06-14 21:16 UTC, UEHG260899 approved these changes

2021-06-15 02:48 UTC, eduardo99ja commented on php/includes/navbar_escritor.php
> +</head>
Esto te lo ahorras usando el header
```php
<?php
require_once(realpath(dirname(__DIR__) . '/includes/header.php'));
?>
```

2021-06-15 02:49 UTC, eduardo99ja requested changes
Usar el include de header en navbar del escritor

2021-06-15 15:57 UTC, eduardo99ja approved these changes

2021-06-15 15:58 UTC, merged